### ISSUE TITLE
[Question] Is it possible to spin a new worker on every `postMessage`?

### ISSUE THREAD

**Issue by jurgenwerk** [yaymukund/ember-web-workers#1]
If yes, what steps do you recommend for implementing such a thing?

Also, thanks for making this add-on :)

**Comment by yaymukund** [comment]
Hi @matixmatix, sorry for the late response. Sorry, the library doesn't support it out of the box. This library is meant for long-lived singleton objects. That said, if you wanted to hack it in, you could write plain JS in the `workers/` directory and use `new Worker()` to spin it up. Just be sure to `close()` your worker from the worker thread (or `worker.terminate()`) when you're all done.
